### ISSUE TITLE
Rotates only CCW

### ISSUE THREAD

**Issue by Nannigalaxy** [TTitanUA/micropython_servo_pdm_360#1]
only works for 1600-2550
is there any solution?

**Comment by TTitanUA** [comment]
Hmm, can you please attach your example code and write the servo model you are using.

**Comment by Nannigalaxy** [comment]
I tested with your manual config code to check
this is the servo: https://robu.in/product/towerpro-mg995-continuous-rotation-360-metal-gear-servo-motor-9-2kg/

**Comment by TTitanUA** [comment]
```from machine import Pin, PWM
from micropython_servo_pdm_360 import ServoPDM360
import utime

# create a PWM servo controller (21 - pin Pico)
servo_pwm = PWM(Pin(21))

# Set the parameters of the servo pulses, more details in the "Documentation" section
freq = 50
min_us = 400
max_us = 2550
dead_zone_us = 150

# create a servo object
servo = ServoPDM360(pwm=servo_pwm, min_us=min_us, max_us=max_us, dead_zone_us=dead_zone_us, freq=freq)



servo.turn_cv(30)
utime.sleep(2)

# turn counter-clockwise with a force of 50
servo.turn_ccv(50)
utime.sleep(2)

servo.stop()
```

Can you try this code? I currently tested it on "MicroPython v1.19.1-854-g35524a6fd on 2023-02-07; Raspberry Pi Pico W with RP2040" and it works.

**Comment by Nannigalaxy** [comment]
yes I ran exactly same 
but I guess this is hardware problem?

**Comment by TTitanUA** [comment]
Maybe. Try to set the duty time manually by using the setDuty method, for example, set it to 1000. If it doesn't work, then try using another pin on the Raspberry Pi. If nothing changes, then either the problem is with the pickup on the control signal (which is unlikely but can happen with such servos), or the problem is with the servo's controller itself.

**Comment by Nannigalaxy** [comment]
Awesome! it worked
changed pin to GP16

I initially tried with pin 16 but didn't test it thoroughly
Thanks buddy

**Comment by Nannigalaxy** [comment]
and another thing is to provide proper power supply 5v to 7.2v

**Comment by TTitanUA** [comment]
I use a power supply of 5V/2A and it works normally. On 8V it is more powerful/faster, but it heats up quickly.

**Comment by Nannigalaxy** [comment]
noted
