### ISSUE TITLE
Specs for joy-it servo FS90R (Com-Motor05)

### ISSUE THREAD

**Issue by philsuess** [TTitanUA/micropython_servo_pdm_360#3]
Hi there,

just getting into servo control with the pico. Thanks for your library, it seems to work great so far.

I have a servo that is not listed. As per here: https://joy-it.net/en/products/COM-Motor05, these are the specs to make it run:

Com-Motor05(joy it FS90R) - min_us=700, max_us=2300, dead_zone_us=90, freq=50

**Comment by TTitanUA** [comment]
Hi, thanks for the configuration! I added it to the Readme.
